getwd()
require(ggplot2)
setwd("C:/Users/anishjoshi500/Downloads/Data Analysis Homework")
#Read Data
data <- read.table("ProdTimeData.txt", header=FALSE)
View(data)
names(data)<-c("pt", "pls")
plot(data$pls, data$pt, xlab="production lot size", ylab="production time")
squarrp<-sqrt(data$pls)
model <- lm(data$pt ~ squarrp, data)
summary(model)
plot(model$fit, model$residuals, main="residual vs. fitted Plot")
abline(h=0)
plot(squarrp, data$pt, xlab="production lot size-sr", ylab="production time")
abline(model)
par(mfrow=c(1,2))
plot(model$fit, model$residuals, main="Residual vs. Fitted Plot")
abline(h=0)
qqnorm(model$residuals)
qqline(model$residuals)
