library(XLConnect)
Data <- readWorksheet(loadWorkbook("C:/Users/anishjoshi500/Downloads/Data Analysis Homework/SaltConc.xlsx"),sheet=1)
View(Data)
model <- lm(Salt ~ Area, Data)
summary(model)
new_data=data.frame(Area=1)
View(new_data)
View(Data)
predict.lm(model, new_data, interval="confidence", level= 0.95, type="response")
predict.lm(model, new_data, interval="prediction", level= 0.95, type="response")
plot(Data$Salt, Data$Area, xlab="Roadway Area", ylab="Salt Concentration")
abline(model)
